### ISSUE TITLE
Python program to add two numbers.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#1]
A simple python program to add two numbers, input given by user.

**Comment by MakendranG** [comment]
Hi @prasadsawant7 

I have worked on this issue and raised a PR https://github.com/prasadsawant7/Python_Programs/pull/53

Kindly merge it.

**Comment by prasadsawant7** [comment]
> Please assign this issue to me, its my first Hacktober Fest event.

Yupp
