### ISSUE TITLE
Python Program for n-th Fibonacci number.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#10]

**Comment by Mohitt0** [comment]
hey @prasadsawant7 assign this to me

**Comment by prasadsawant7** [comment]
> hey @prasadsawant7 assign this to me

Hey @Mohitt0 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022.

**Comment by snehal-s10** [comment]
Please assign me!

**Comment by prasadsawant7** [comment]
> Please assign me!

ok
