### ISSUE TITLE
Python Program to find largest element in an array.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#17]

**Comment by ShrutiSingh04503** [comment]
Hey, I'll love to work on this issue, Would appreciate it if you assign me.

**Comment by prasadsawant7** [comment]
> Hey, I'll love to work on this issue, Would appreciate it if you assign me.

Hey @ShrutiSingh04503 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by Riya1812** [comment]
Assign this to me please.
