### ISSUE TITLE
Python program to find maximum of two numbers.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#2]
Find largest number among two numbers given input by user.

**Comment by Mohitt0** [comment]
hey @prasadsawant7 assign this to me

**Comment by Aru8416** [comment]
Its my first Hacktober Fest please assign me.

**Comment by prasadsawant7** [comment]
> Its my first Hacktober Fest please assign me.

Sure.

**Comment by prasadsawant7** [comment]
> hey @prasadsawant7 assign this to me

Hey @Mohitt0 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022
