### ISSUE TITLE
Python Program to check if given array is Monotonic.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#22]
An array is monotonic if it is either monotone increasing or monotone decreasing.

An array nums is monotone increasing if for all i <= j, nums[i] <= nums[j]. An array nums is monotone decreasing if for all i <= j, nums[i] >= nums[j].

Given an integer array nums, return true if the given array is monotonic, or false otherwise.

**Example 1**
`Input: nums = [1,2,2,3]
Output: true`

**Example 2**
`Input: nums = [1,3,2]
Output: false`

**Comment by riya-215** [comment]
Assign it to me!

**Comment by prasadsawant7** [comment]
> Assign it to me!

Sure
