### ISSUE TITLE
Python Program to find sum of elements in list.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#29]

**Comment by srijani18** [comment]
Hey @prasadsawant7 could you please let me do this one? Thank you!

**Comment by prasadsawant7** [comment]
> Hey @prasadsawant7 could you please let me do this one? Thank you!

Hey @srijani18 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by Rupali887** [comment]
Assign me please!

**Comment by prasadsawant7** [comment]
> Assign me please!

sure.
