### ISSUE TITLE
Python Program to find smallest number in a list.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#31]

**Comment by ShrutiSingh04503** [comment]
Hey, I'll love to work on this issue, Would appreciate it if you assign me.

**Comment by prasadsawant7** [comment]
> Hey, I'll love to work on this issue, Would appreciate it if you assign me.

Hey @ShrutiSingh04503 sorry, Stay tuned with me and I invite you to my another repo which will be named as Hacktoberfest-2022. There you can contribute freely. I'm sorry this repo is only for my college friends only, because they are new to Open Source. So, again sorry and I welcome you to my another repo Hacktoberfest-2022.

**Comment by Rupali887** [comment]
Assign me please!

**Comment by prasadsawant7** [comment]
> Assign me please!

sure.
