### ISSUE TITLE
Python Program to find largest number in a list.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#32]

**Comment by PanikaGupta** [comment]
hey! please assign this to me

**Comment by prasadsawant7** [comment]
> hey @prasadsawant7 assign this to me

Hey @Mohitt0 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by prasadsawant7** [comment]
> hey! please assign this to me

Hey @PanikaGupta contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by Rupali887** [comment]
Assign me please!

**Comment by prasadsawant7** [comment]
> Assign me please!

sure.
