### ISSUE TITLE
Python Program to print even numbers in a list.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#35]

**Comment by Mohitt0** [comment]
hey @prasadsawant7 assign this to me

**Comment by radhika2503** [comment]
@prasadsawant7 please assign this to me.

**Comment by prasadsawant7** [comment]
> hey @prasadsawant7 assign this to me

Hey @Mohitt0 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by prasadsawant7** [comment]
> @prasadsawant7 please assign this to me.

Hey @radhika2503 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by Rupali887** [comment]
Assign me please!

**Comment by prasadsawant7** [comment]
> Assign me please!

sure.
