### ISSUE TITLE
Python Program to print all odd numbers in a range.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#38]

**Comment by Mohitt0** [comment]
hey @prasadsawant7 assign this to me

**Comment by srijani18** [comment]
@prasadsawant7 hey, could you please assign this to me? This is my first pull request, I'll be more than happy to begin with this!

**Comment by prasadsawant7** [comment]
> hey @prasadsawant7 assign this to me

Hey @Mohitt0 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by prasadsawant7** [comment]
> @prasadsawant7 hey, could you please assign this to me? This is my first pull request, I'll be more than happy to begin with this!

Hey @srijani18 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by bhavyaa02** [comment]
Please assign this issue to me!

**Comment by prasadsawant7** [comment]
> Please assign this issue to me!

Sure

**Comment by Mohitt0** [comment]
When you create another repo
