### ISSUE TITLE
Python Program to print negative numbers in a list.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#40]

**Comment by radhika2503** [comment]
hey please assign me this.
this is my first attempt.

**Comment by prasadsawant7** [comment]
> hey please assign me this. this is my first attempt.

Hey @radhika2503 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by prasadsawant7** [comment]
> Hey @prasadsawant7, can you please assign this issue to me? I'll be more than happy to work on the same.

Hey @Daksh-Raghuvanshi contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022.

**Comment by bhavyaa02** [comment]
Please assign this issue to me!

**Comment by prasadsawant7** [comment]
> Please assign this issue to me!

Sure
