### ISSUE TITLE
Python Program for compound interest.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#5]

**Comment by coderoshan18093** [comment]
can i work on this?

**Comment by Aru8416** [comment]
Its my first Hacktober Fest please assign me.

**Comment by prasadsawant7** [comment]
> Its my first Hacktober Fest please assign me.

Sure.

**Comment by prasadsawant7** [comment]
> can i work on this?

Hey @coderoshan18093 , In few hours i'll be creating a repo, you can contribute there. Repo name will be Hacktoberfest-2022
