### ISSUE TITLE
Python Program to check Armstrong Number.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#6]

**Comment by radhika2503** [comment]
hey can i work on this?
this is my first hacktoberfest.

**Comment by prasadsawant7** [comment]
> hey can i work on this? this is my first hacktoberfest.

Hey @radhika2503 contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022. Surely I'll accept your PR, please cooperate me.

**Comment by snehal-s10** [comment]
Please assign me!

**Comment by prasadsawant7** [comment]
> Please assign me!

ok
