### ISSUE TITLE
Python Program for Program to find area of a circle.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/Python_Programs#7]

**Comment by Daksh-Raghuvanshi** [comment]
Hey @prasadsawant7, please assign me this issue, I'll be happy to work on it.

**Comment by prasadsawant7** [comment]
> Hey @prasadsawant7, please assign me this issue, I'll be happy to work on it.

Hey @Daksh-Raghuvanshi contribute to my another repo which i'll be creating next few hours. This repo is only for my college friends. Sorry for it. The repo which i'll be creating is Hacktoberfest-2022

**Comment by snehal-s10** [comment]
Please assign me!

**Comment by prasadsawant7** [comment]
> Please assign me!

ok
